set_property IOSTANDARD TMDS_33 [get_ports TMDS_IN_clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_EDID_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_EDID_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports binary_data]
set_property IOSTANDARD LVCMOS33 [get_ports binary_data_valid]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_IN_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_IN_data_p[1]}]
set_property PACKAGE_PIN N18 [get_ports clk]
set_property PACKAGE_PIN T12 [get_ports rst_n]
set_property PACKAGE_PIN V16 [get_ports {TMDS_IN_data_p[0]}]

set_property PACKAGE_PIN T17 [get_ports TMDS_IN_clk_p]
set_property PACKAGE_PIN V17 [get_ports {TMDS_IN_data_p[2]}]
set_property PACKAGE_PIN W14 [get_ports {TMDS_IN_data_p[1]}]
set_property PACKAGE_PIN R17 [get_ports binary_data_valid]
set_property PACKAGE_PIN P18 [get_ports binary_data]
set_property PACKAGE_PIN Y18 [get_ports HDMI_EDID_sda_io]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/dvi2rgb_0/U0/TMDS_ClockingX/CLK_IN_hdmi_clk]

set_property PACKAGE_PIN Y16 [get_ports HDMI_EDID_scl_io]
