set_property PACKAGE_PIN N18 [get_ports clk]
set_property PACKAGE_PIN T12 [get_ports rst_n]
set_property PACKAGE_PIN R19 [get_ports EDID_RX_scl_io]
set_property PACKAGE_PIN T19 [get_ports EDID_RX_sda_io]
set_property PACKAGE_PIN U18 [get_ports HDMI_RX_clk_p]
set_property PACKAGE_PIN P19 [get_ports {HDMI_RX_HPA[0]}]
set_property PACKAGE_PIN N20 [get_ports {HDMI_RX_data_p[2]}]
set_property PACKAGE_PIN T20 [get_ports {HDMI_RX_data_p[1]}]
set_property PACKAGE_PIN V20 [get_ports {HDMI_RX_data_p[0]}]
set_property PACKAGE_PIN Y16 [get_ports HDMI_TX_clk_p]
set_property PACKAGE_PIN V18 [get_ports {HDMI_TX_HPD[0]}]
set_property PACKAGE_PIN W14 [get_ports {HDMI_TX_data_p[2]}]
set_property PACKAGE_PIN V16 [get_ports {HDMI_TX_data_p[1]}]
set_property PACKAGE_PIN T17 [get_ports {HDMI_TX_data_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports EDID_RX_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports EDID_RX_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_RX_HPA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_TX_HPD[0]}]


