# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/rom_image/rom_image.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_image || ORIG_REF_NAME==rom_image} -quiet] -quiet

# XDC: ip/rom_image/rom_image_ooc.xdc
