# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_uiFDMA_0_1/system_uiFDMA_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uiFDMA_0_1 || ORIG_REF_NAME==system_uiFDMA_0_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_0/system_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_5/system_axi_mem_intercon_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_5 || ORIG_REF_NAME==system_axi_mem_intercon_5} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_150M_0 || ORIG_REF_NAME==system_rst_ps7_0_150M_0} -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/Zynq7010_eink_controller/controller/Z7_Lite/PL_RW_DDR/PL_RW_DDR.gen/sources_1/bd/system/system_ooc.xdc
