webtalk_init -webtalk_dir C:/Users/Admin/Desktop/Zynq7010_eink_controller/controller/Z7_Lite/gray2binarization/gray2binarization.sim/sim_1/synth/timing/xsim/xsim.dir/gray2binarization_tb_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 10 11:13:27 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3979bdeb-3ee6-440b-9661-2c8405fa1775" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aefa0d39500b4439b38cfaf33b8d01a2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4200 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7904_KB" -context "xsim\\usage"
webtalk_transmit -clientid 12305746 -regid "" -xml C:/Users/Admin/Desktop/Zynq7010_eink_controller/controller/Z7_Lite/gray2binarization/gray2binarization.sim/sim_1/synth/timing/xsim/xsim.dir/gray2binarization_tb_time_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Admin/Desktop/Zynq7010_eink_controller/controller/Z7_Lite/gray2binarization/gray2binarization.sim/sim_1/synth/timing/xsim/xsim.dir/gray2binarization_tb_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Admin/Desktop/Zynq7010_eink_controller/controller/Z7_Lite/gray2binarization/gray2binarization.sim/sim_1/synth/timing/xsim/xsim.dir/gray2binarization_tb_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
