######################################################################
#
# File name : eink_controller_ed108_tb.udo
# Created on: Sat May 21 15:43:48 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
