######################################################################
#
# File name : eink_controller_ed108_tb_wave.do
# Created on: Sat May 21 15:43:48 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
